### ISSUE TITLE
[ERROR] Exception in thread "main" com.sun.tools.javac.util.Abort

### ISSUE THREAD

**Issue by ghost** [smoope/j2objc-maven-plugin#17]
I am getting this error while trying to convert my code using the j2objc maven plugin:
`[ERROR] Exception in thread "main" com.sun.tools.javac.util.Abort
[ERROR] 	at com.sun.tools.javac.comp.Check.completionError(Check.java:287)
[ERROR] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:584)
[ERROR] 	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:638)
[ERROR] 	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:631)
[ERROR] 	at com.sun.tools.javac.comp.MemberEnter.attribImportType(MemberEnter.java:834)
[ERROR] 	at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:558)
[ERROR] 	at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:571)
[ERROR] 	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
[ERROR] 	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:449)
[ERROR] 	at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:528)
[ERROR] 	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
[ERROR] 	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
[ERROR] 	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1038)
[ERROR] 	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
[ERROR] 	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
[ERROR] 	at com.sun.tools.javac.comp.Enter.complete(Enter.java:493)
[ERROR] 	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
[ERROR] 	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
[ERROR] 	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:316)
[ERROR] 	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:359)
[ERROR] 	at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:344)
[ERROR] 	at com.google.devtools.j2objc.javac.JavacParser.parseFiles(JavacParser.java:197)
[ERROR] 	at com.google.devtools.j2objc.pipeline.FileProcessor.processBatch(FileProcessor.java:137)
[ERROR] 	at com.google.devtools.j2objc.pipeline.FileProcessor.processInputs(FileProcessor.java:67)
[ERROR] 	at com.google.devtools.j2objc.pipeline.TranslationProcessor.processInputs(TranslationProcessor.java:83)
[ERROR] 	at com.google.devtools.j2objc.J2ObjC.run(J2ObjC.java:127)
[ERROR] 	at com.google.devtools.j2objc.J2ObjC.main(J2ObjC.java:176)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.436 s
[INFO] Finished at: 2023-09-25T14:57:11+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.smoope.utils:j2objc-maven-plugin:1.1.4:convert (default-cli) on project otx-runner: j2objc translator had errors - check log -> [Help 1]`

Up until recently the conversion ran without issues on all of my projects using the same config. I suspect that auto updating JDK / Maven versions might be the root cause, but  I still face this when changing to older versions of both.

Any idea what could be causing this? I'm also unsure of how to get further logs / error info.

This is my plugin configuration:
`<plugin>
				<groupId>com.smoope.utils</groupId>
				<artifactId>j2objc-maven-plugin</artifactId>
				<version>1.1.4</version>
				<configuration>
					<skipParent>true</skipParent>
					<failOnErrors>true</failOnErrors>
					<j2objcPath>/Users/j2objc-2.8/j2objc</j2objcPath>
					<d>${project.build.directory}/j2objc/src</d>
					<sourcePath>${project.basedir}/src/main/java</sourcePath>
					<encoding>CP1252</encoding>
					<useArc>true</useArc>
				</configuration>
			</plugin>`

**Comment by vicmosin** [comment]
Hi @kpit-vchck , did you check that downgraded JDK is indeed used within the project? I can't really say why it happens, but stacktrace points to javac which is JDK-related thing. I also found something similar here: https://github.com/google/j2objc/issues/1034 where they also suggest to upgrade the lib itself. So maybe try to play with different. j2obc and java versions
